<a href="https://colab.research.google.com/github/ggzlemos/busca-cega/blob/main/busca_cega.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# O Problema
Sliding Puzzle - Bloco Deslizante

In [ ]:
# !wget -qq https://miro.medium.com/max/700/1*W7jg4GmEjGBypd9WPktasQ.gif
from IPython.display import Image
Image(url='https://miro.medium.com/max/700/1*W7jg4GmEjGBypd9WPktasQ.gif',width=200)

# Resolver o quebra-cabeças usando Buscas

###Importações:

In [1]:
import numpy as np

###Classe para representar os estados:

In [2]:
class Nodo:
  def __init__(self, estado):       
    self.estado = estado
    self.caminho = []
    self.pai = None

  def getEstado(self):
    return self.estado

  def setPai(self, nodo):
    self.pai = nodo

  def getPai(self):
    return self.pai  
   
  def coordVazio(self):
    i, j = np.where(self.estado == 0)
    return i[0], j[0]

  def constroiCaminho(self):
    caminho = []
    filho = self
    pai = self.getPai()
    while pai != None:
      caminho.append(pai.getEstado())
      pai = pai.getPai()    
    caminho.reverse()
    caminho.append(self.estado)
    self.caminho = caminho

  def imprimeCaminho(self):
    self.constroiCaminho()
    print("Resultado:")
    for i in self.caminho:
      print(i)
    
  def getProfundidade(self):
    return len(self.caminho)-1

  def getDim(self):
    return self.estado.shape

  def geraEstados(self):
    vizinhos = []  
    I, J = self.getDim()
    i, j = self.coordVazio() 
    dj = np.array([-1, 1, 0, 0])
    di = np.array([0, 0, 1, -1])
        
    for k in range(0, 4):
      i_novo = i + di[k]
      j_novo = j + dj[k]  
      if not i_novo < 0 and not j_novo < 0:
        if not i_novo >= I and not j_novo >= J:
          novo_vizinho = self.estado.copy()       
          novo_vizinho[i][j], novo_vizinho[i_novo][j_novo] = novo_vizinho[i_novo][j_novo], novo_vizinho[i][j]
          novo_vizinho = Nodo(novo_vizinho)        
          vizinhos.append(novo_vizinho)                  
    return vizinhos 

###Função auxiliar para verificar se um nodo já foi visitado: 

In [5]:
def foi_visitado(visitados, estado):
  for i in visitados:
    if np.array_equal(i, estado):
      return True
  return False

## Busca em largura

In [3]:
def bfs(estado_inicial, estado_final):
  fila = [estado_inicial]
  visitados = []

  while len(fila) > 0:     
    nodo = fila.pop(0)
    visitados.append(nodo.getEstado())
    if np.array_equal(nodo.getEstado(), estado_final):             
        return nodo       
    vizinhanca = nodo.geraEstados()
    for proximo in vizinhanca:               
      if not foi_visitado(visitados, proximo.getEstado()):                                                        
          fila.append(proximo)
          proximo.setPai(nodo)

####Instância do problema para ser resolvida usando Busca em Largura:

In [6]:
estado_inicial = Nodo(np.array([1,2,3,4,5,6,0,7,8]).reshape((3,3)))
estado_final = np.array([1,2,3,4,5,6,7,8,0]).reshape((3,3))
resultado = bfs(estado_inicial, estado_final)
resultado.imprimeCaminho()

Resultado:
[[1 2 3]
 [4 5 6]
 [0 7 8]]
[[1 2 3]
 [4 5 6]
 [7 0 8]]
[[1 2 3]
 [4 5 6]
 [7 8 0]]


## Busca em profundidade

In [7]:
def dfs(estado_inicial, estado_final):
  pilha =[estado_inicial]
  visitados = []
  while len(pilha) > 0: 
    nodo = pilha.pop()    
    visitados.append(nodo.getEstado())
    if np.array_equal(nodo.getEstado(), estado_final):          
        return nodo    
    vizinhanca = nodo.geraEstados()           
    for proximo in vizinhanca:
      if not foi_visitado(visitados, proximo.getEstado()):                                                 
        pilha.append(proximo)               
        proximo.setPai(nodo)                           
  return Nodo(np.array([]))   #retorna um nodo vazio caso falhe em encontrar solução 

####Instância do problema para ser resolvida usando Busca em Profundidade:




In [8]:
a = np.array([1,2,3,4,5,6,7,0,8]).reshape((3,3))
estado_final = np.array([1,2,3,4,5,6,7,8,0]).reshape((3,3))
estado_inicial = Nodo(a)
resultado = dfs(estado_inicial, estado_final)
resultado.imprimeCaminho()

Resultado:
[[1 2 3]
 [4 5 6]
 [7 0 8]]
[[1 2 3]
 [4 0 6]
 [7 5 8]]
[[1 0 3]
 [4 2 6]
 [7 5 8]]
[[1 3 0]
 [4 2 6]
 [7 5 8]]
[[1 3 6]
 [4 2 0]
 [7 5 8]]
[[1 3 6]
 [4 2 8]
 [7 5 0]]
[[1 3 6]
 [4 2 8]
 [7 0 5]]
[[1 3 6]
 [4 0 8]
 [7 2 5]]
[[1 0 6]
 [4 3 8]
 [7 2 5]]
[[1 6 0]
 [4 3 8]
 [7 2 5]]
[[1 6 8]
 [4 3 0]
 [7 2 5]]
[[1 6 8]
 [4 3 5]
 [7 2 0]]
[[1 6 8]
 [4 3 5]
 [7 0 2]]
[[1 6 8]
 [4 0 5]
 [7 3 2]]
[[1 0 8]
 [4 6 5]
 [7 3 2]]
[[1 8 0]
 [4 6 5]
 [7 3 2]]
[[1 8 5]
 [4 6 0]
 [7 3 2]]
[[1 8 5]
 [4 6 2]
 [7 3 0]]
[[1 8 5]
 [4 6 2]
 [7 0 3]]
[[1 8 5]
 [4 0 2]
 [7 6 3]]
[[1 0 5]
 [4 8 2]
 [7 6 3]]
[[1 5 0]
 [4 8 2]
 [7 6 3]]
[[1 5 2]
 [4 8 0]
 [7 6 3]]
[[1 5 2]
 [4 8 3]
 [7 6 0]]
[[1 5 2]
 [4 8 3]
 [7 0 6]]
[[1 5 2]
 [4 0 3]
 [7 8 6]]
[[1 0 2]
 [4 5 3]
 [7 8 6]]
[[1 2 0]
 [4 5 3]
 [7 8 6]]
[[1 2 3]
 [4 5 0]
 [7 8 6]]
[[1 2 3]
 [4 5 6]
 [7 8 0]]


##Algumas considerações sobre o uso de memória:


####Embora encontre a solução do problemas em número menor movimentos, a busca em largura utiliza mais memória do que a busca em profundidade. Isso acontece pois a busca em largura encontra a solução mais 'rasa', ou seja, no menor número de camadas exploradas possíveis (com isso, dependendo do problema, não garante que a solução encontrada é ótima). Para isso, adiciona à uma estrutura de dados (fila) todos os estados daquela camada.

####Em contrapartida, o algoritmo de busca em profundidade gasta menos memória por não armazenar todos os estados de uma camada da árvore de estados, porém encontra uma solução mais "profunda", ou seja, em maior número de movimentos. Além disso, o algoritmo de busca em profundidade não garante encontrar uma solução para o problema.

####Na prática, nenhum dos algoritmos apresentados se mostrou muito útil para solucionar o problema proposto. O algoritmo de busca em largura, em alguns casos, pode estourar a capacidade de memória por armazenar os estados das camadas e o algoritmo de busca em profundidade pode não encontrar uma solução para o problema.   

